### ISSUE TITLE
[Bug]: Cannot open / create a report via cli

### ISSUE THREAD

**Issue by kwonoj** [web-infra-dev/rsdoctor#482]
### Version

```sh
System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 80.20 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 128.0.6613.113
    Safari: 17.6
  npmPackages:
    @rsdoctor/webpack-plugin: ^0.3.11 => 0.3.11
    webpack@5.94.0
```

### Details

When running cli, getting some error message instead of opening up the report.

### Reproduce link

-

### Reproduce Steps

```
[@rsdoctor/cli] ✖ Cannot create a string longer than 0x1fffffe8 characters

Error: Cannot create a string longer than 0x1fffffe8 characters
    at Buffer.toString (node:buffer:813:17)
    at decompressText (/Users/ohjoong.kwon/.npm/_npx/d63fae48b24039a6/node_modules/@rsdoctor/utils/dist/cjs/common/algorithm.js:49:83)
    at fetchShardingData (/Users/ohjoong.kwon/.npm/_npx/d63fae48b24039a6/node_modules/@rsdoctor/utils/dist/cjs/common/manifest.js:41:97)
    at async /Users/ohjoong.kwon/.npm/_npx/d63fae48b24039a6/node_modules/@rsdoctor/utils/dist/cjs/common/manifest.js:55:18
    at async Promise.all (index 10)
    at async Object.fetchShardingFiles (/Users/ohjoong.kwon/.npm/_npx/d63fae48b24039a6/node_modules/@rsdoctor/utils/dist/cjs/common/manifest.js:44:17)
    at async action (/Users/ohjoong.kwon/.npm/_npx/d63fae48b24039a6/node_modules/@rsdoctor/cli/dist/commands/analyze.js:77:19)
    at async Object.handler (/Users/ohjoong.kwon/.npm/_npx/d63fae48b24039a6/node_modules/@rsdoctor/cli/dist/index.js:63:11)
```

**Comment by easy1090** [comment]
what the size of the .rsdoctor dir?

which dir is biggest in .rsdoctor? chunkgraph or  moduleCodeMap or loaders ?

**Comment by kwonoj** [comment]
```
6.0M	./build/.rsdoctor//moduleGraph
 76K	./build/.rsdoctor//packageGraph
189M	./build/.rsdoctor//moduleCodeMap
172K	./build/.rsdoctor//plugin
1.5M	./build/.rsdoctor//otherReports
4.0K	./build/.rsdoctor//envinfo
 27M	./build/.rsdoctor//loader
8.0K	./build/.rsdoctor//configs
800K	./build/.rsdoctor//errors
238M	./build/.rsdoctor//chunkGraph
4.0K	./build/.rsdoctor//resolver
4.0K	./build/.rsdoctor//summary
472M	./build/.rsdoctor/
```

**Comment by easy1090** [comment]
Try this configuration: https://rsdoctor.dev/config/options/options#features
```ts
feature: ['lite', 'loader','plugins','bundle']
```

**Comment by easy1090** [comment]
@kwonoj This case need use `lite` mode.There is only a lack of source code and bundle product code, and there is no lack of functions.https://rsdoctor.dev/config/options/options#mode

**Comment by kwonoj** [comment]
> lack of source code and bundle product code,

I hoped to get a full analytics, but not an immediate concern. Going to close issue for now - however if the symptom with larget output can be fixed it'd be great.
